# Host: xelo-nixos
#
# Intel laptop. Boots straight into a Niri (Wayland) session for `xelo`.
# Everything here is either truly machine-specific (hardware, hostname,
# stateVersion) or a one-line pointer into ../../modules/system.
{ ... }:
{
  imports = [
    # Generated by `nixos-generate-config`. Describes disks, filesystems and
    # CPU. Regenerate on a NEW machine with:
    #   sudo nixos-generate-config --show-hardware-config > hardware-configuration.nix
    ./hardware-configuration.nix

    # All the reusable system configuration, split by topic.
    ../../modules/system
  ];

  networking.hostName = "xelo-nixos";

  # The NixOS release this machine was first installed from. It pins defaults
  # for stateful things (databases, etc). Do NOT bump it just to get new
  # packages — that is what `nix flake update` is for. See `man configuration.nix`.
  system.stateVersion = "25.11";
}
